### ISSUE TITLE
Add sass and other pre-proccessors support

### ISSUE THREAD

**Issue by TiroZit** [vituum/vite-plugin-juice#1]
Hi, @lubomirblazekcz !

I have a problem. I don't understand how to add support for `sass` preprocessors

**Comment by lubomirblazekcz** [comment]
Hmm, this won't work currently. You can only use PostCSS now, I though that lang="sass" syntax was supported by Vite, but it's not. So the description in README.md is not correct, I will change it. 

Support for sass, less etc. is missing currently.

**Comment by lubomirblazekcz** [comment]
I've added a workaround in v0.1.7, you can add following link in the head of email and process the file manually (Eg. with https://sass-lang.com/documentation/js-api/) 

```html
<link rel="stylesheet" data-href="/src/email.less" data-juice-link>
```

```js
import juice from '@vituum/vite-plugin-juice'

export default {
  plugins: [
    juice({ 
      handleLinks: async (href) => {
         // return processed sass css
      }
    })
  ]
}
```
